# Generated by Django 4.2.30 on 2026-04-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'activities',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Bienvenido a GymApp', max_length=200)),
                ('about_title', models.CharField(default='Quiénes Somos', max_length=200)),
                ('about_description', models.TextField(default='')),
                ('activities_title', models.CharField(default='Nuestras Actividades', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración de inicio',
                'verbose_name_plural': 'Configuración de inicio',
                'db_table': 'home_config',
            },
        ),
    ]
