# Generated by Django 4.2.30 on 2026-04-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageconfig',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='map_embed_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='schedule',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='whatsapp_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
