# Generated by Django 4.2.30 on 2026-04-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepageconfig_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('hours', models.TextField(help_text='Una hora por línea, ej: Lunes - Viernes: 06:00 - 22:00')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'schedules',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='homepageconfig',
            name='schedule',
        ),
    ]
