# Generated by Django 4.2.30 on 2026-04-19 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('muscle', models.CharField(choices=[('PECTORAL', 'Pectoral'), ('DORSAL', 'Dorsal'), ('BICEPS', 'Bíceps'), ('TRICEPS', 'Tríceps'), ('HOMBRO', 'Hombro'), ('CUADRICEPS', 'Cuádriceps'), ('FEMORALES', 'Femorales'), ('GLUTEOS', 'Glúteos'), ('ABDOMINALES', 'Abdominales'), ('GASTROCNEMIO', 'Gastrocnemio')], max_length=20)),
                ('muscle_group', models.CharField(choices=[('PECHO_HOMBRO', 'Pecho y Hombro'), ('PIERNAS', 'Piernas'), ('ESPALDA_BICEP', 'Espalda y Bícep')], max_length=20)),
                ('description', models.TextField()),
                ('video_tutorial', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='UserExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(default=0)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exercises', to='exercises.exercise')),
            ],
            options={
                'db_table': 'user_exercises',
            },
        ),
        migrations.CreateModel(
            name='UserExerciseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('weight', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='exercises.userexercise')),
            ],
            options={
                'db_table': 'user_exercise_history',
            },
        ),
    ]
