# Generated by Django 4.2.30 on 2026-04-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroupCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_group', models.CharField(choices=[('PECHO_HOMBRO', 'Pecho y Hombro'), ('PIERNAS', 'Piernas'), ('ESPALDA_BICEP', 'Espalda y Bícep')], max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='muscle_groups/')),
            ],
            options={
                'db_table': 'muscle_group_cards',
            },
        ),
    ]
