# Generated by Django 4.2.30 on 2026-04-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_musclegroupcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclegroupcard',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
